import { UnaskedQuestion } from '../types';

export class ClientExportService {
  public static generateMarkdownReport(topic: string, questions: UnaskedQuestion[]): string {
    const lines = [
      `# 🧠 Human Curiosity Discovery Report: ${topic}`,
      `*Generated by Human Curiosity Engine — AI That Discovers Unasked Questions*`,
      `*Date:* ${new Date().toLocaleDateString()}`,
      `\n---\n`
    ];

    questions.forEach((q, i) => {
      lines.push(`## 0${i + 1}. ${q.title}`);
      lines.push(`**Curiosity Score:** ${q.curiosity_score}/100 | **Category:** ${q.category}`);
      lines.push(`\n### Hidden Blindspot\n${q.hidden_blindspot}`);
      lines.push(`\n### Why It Matters\n${q.why_it_matters}`);
      lines.push(`\n### 2050 Future Horizon\n${q.future_impact.year_2050}`);
      lines.push(`\n### Startup Opportunity\n* **Title:** ${q.startup_opportunity.title}\n* **Solution:** ${q.startup_opportunity.solution}`);
      lines.push(`\n---\n`);
    });

    return lines.join('\n');
  }

  public static generateCitation(topic: string): string {
    const slug = topic.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 20);
    return `@article{${slug}_curiosity_engine_2026,
  author = {Mahes, Vijay},
  title = {Unasked Questions and Systemic Blindspots in ${topic}},
  journal = {Human Curiosity Engine Discovery Repository},
  year = {2026},
  url = {https://github.com/vijaymahes9080/HUMAN-CURIOSITY-ENGINE}
}`;
  }
}
