import React, { useState } from 'react';
import { X, Download, Copy, Check, FileCode, FileText } from 'lucide-react';
import { UnaskedQuestion } from '../../types';
import { soundManager } from '../../services/sound';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  topic: string;
  questions: UnaskedQuestion[];
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  topic,
  questions
}) => {
  const [format, setFormat] = useState<'markdown' | 'latex' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = () => {
    let md = `# 🧠 Curiosity Discovery Report: ${topic}\n\n`;
    md += `*Generated by Human Curiosity Engine*\n\n---\n\n`;
    questions.forEach((q, idx) => {
      md += `### ${idx + 1}. ${q.title}\n`;
      md += `* **Curiosity Score:** ${q.curiosity_score}/100\n`;
      md += `* **Category:** ${q.category}\n`;
      md += `* **Hidden Blindspot:** ${q.hidden_blindspot}\n`;
      md += `* **Why It Matters:** ${q.why_it_matters}\n\n`;
    });
    return md;
  };

  const generateLaTeX = () => {
    let tex = `% Curiosity Discovery Report: ${topic}\n\\documentclass{article}\n\\begin{document}\n\\title{Curiosity Discovery: ${topic}}\n\\maketitle\n\n`;
    questions.forEach((q, idx) => {
      tex += `\\section*{${idx + 1}. ${q.title}}\n\\textbf{Curiosity Score:} ${q.curiosity_score}/100 \\\\\n\\textbf{Blindspot:} ${q.hidden_blindspot}\n\n`;
    });
    tex += `\\end{document}`;
    return tex;
  };

  const content = format === 'markdown' ? generateMarkdown() : format === 'latex' ? generateLaTeX() : JSON.stringify({ topic, questions }, null, 2);

  const handleCopy = () => {
    soundManager.playClick();
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const handleDownload = () => {
    soundManager.playClick();
    const ext = format === 'markdown' ? 'md' : format === 'latex' ? 'tex' : 'json';
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `curiosity-report-${topic.toLowerCase().replace(/\s+/g, '-')}.${ext}`;
    a.click();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md">
      <div className="relative w-full max-w-2xl bg-[#0D121E] border border-white/10 rounded-2xl p-6 shadow-2xl space-y-4">
        <div className="flex items-center justify-between border-b border-white/10 pb-3">
          <div className="flex items-center gap-2">
            <Download className="w-5 h-5 text-cyan-400" />
            <h3 className="font-heading font-bold text-lg text-white">Export Curiosity Discovery Report</h3>
          </div>
          <button
            onClick={() => {
              soundManager.playClick();
              onClose();
            }}
            className="p-1 rounded-lg text-slate-400 hover:text-white"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="flex items-center gap-2">
          {(['markdown', 'latex', 'json'] as const).map((fmt) => (
            <button
              key={fmt}
              onClick={() => {
                soundManager.playClick();
                setFormat(fmt);
              }}
              className={`px-3 py-1.5 rounded-lg text-xs font-mono uppercase font-bold transition-all cursor-pointer ${
                format === fmt
                  ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40'
                  : 'bg-slate-900 text-slate-400 border border-white/5'
              }`}
            >
              {fmt}
            </button>
          ))}
        </div>

        <textarea
          readOnly
          value={content}
          rows={12}
          className="w-full p-3 rounded-xl bg-slate-950 border border-white/10 text-slate-300 font-mono text-xs focus:outline-none select-all"
        />

        <div className="flex items-center justify-end gap-3 pt-2">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 text-slate-200 hover:text-white flex items-center gap-1.5 transition-all cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Text'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-5 py-2 rounded-xl text-xs font-semibold bg-gradient-to-r from-cyan-500 to-blue-600 text-white hover:from-cyan-400 flex items-center gap-1.5 shadow-lg shadow-cyan-500/20 transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download File</span>
          </button>
        </div>
      </div>
    </div>
  );
};
